### ISSUE TITLE
[DynaFlow] Report component results

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/powsybl-dynawo#103]
* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

The dynaflow integration provides an empty list of `ComponentResult`, in the `LoadFlowResult`.

* **What is the expected behavior?**

We should try to provide information about the executed computations in component results.
In particular, knowing the status of the computation on network components will be very important for users.

* **What is the motivation / use case for changing the behavior?**

In particular, being able to know if the computation has been successful or not.

**Implementation question**
Does it require an evolution in DynaFlow to retrieve those informations ?

**Comment by dimbdr** [comment]
Is this already addressed by the following commit?
https://github.com/powsybl/powsybl-dynawo/commit/d0e16263da2cf89820108bfbdceccfffe76cc642

**Comment by sylvlecl** [comment]
Indeed it is, we can close this issue.

Note however that if dynaflow is able to carry computations on multiple connected components, we could improve it by creating a "component result" for each connected component.

Do you know if that is the case ?

**Comment by dimbdr** [comment]
Well, I talked to @marcochiaramello, it seems Dynaflow is not ready to bring this feature, yet.
I don't have any clue about when it is going to be available.

**Comment by sylvlecl** [comment]
Ok thanks for the feedback! it's clearly not an issue at the moment.
