### ISSUE TITLE
DynaFlow: add StartingPointMode parameter

### ISSUE THREAD

**Issue by marcochiaramello** [powsybl/powsybl-dynawo#125]
* **Do you want to request a *feature* or report a *bug*?**

feature

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

Being able to set dynaflow parameter "StartingPointMode". This parameter can take two string values, warm or flat. No default value should be provided

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
@marcochiaramello "No default value should be provided", what is the behaviour of the simulator in that case?

**Comment by marcochiaramello** [comment]
> @marcochiaramello "No default value should be provided", what is the behaviour of the simulator in that case?

The default values are managed directly inside DynaFlow launcher

**Comment by geofjamg** [comment]
> > @marcochiaramello "No default value should be provided", what is the behaviour of the simulator in that case?
> 
> The default values are managed directly inside DynaFlow launcher. There, the default value, is "warm"

So what will happen with a forecast case in UCTE format for instance, where there is no provided initial state in the network?
