### ISSUE TITLE
Missing attributes in StandardBus

### ISSUE THREAD

**Issue by flo-dup** [powsybl/powsybl-dynawo#150]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the dyd file, `StandardBus` which corresponds to `Bus` library includes
- no macro static reference
- no parameterSetId

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Include a `StandardBus` and look at the dyd generated file. See for instance DynamicModelsXmlTest::writeDynamicModel with reference file:
https://github.com/powsybl/powsybl-dynawo/blob/00d9e7c13493eaad7d4e2c03c39b548aa65ec5a8/dynawaltz/src/test/resources/dyd.xml#L30

**What is the expected behavior?**
Including
- Macro static references
- parameterSetId
Or add comment explaining why those parameters are not needed.

**Comment by dimbdr** [comment]
Based on examples of dyd files working in Dynawo (for instance : https://github.com/dynawo/dynawo/blob/master/nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.dyd)
There are no parFile and parId attributes in the dyd associated to the bus declaration, so there's no need for parameterSetId attribute to be set.
As for the macro static reference, I did not find any example which contains the info, so I assume there's no use for the bus case. But I can't confirm on my own.

**Comment by gautierbureau** [comment]
For macro static reference are always optional so that's why they are not present in the example. But for me there is no reason as why there should not be one. I will try to add them for Bus, Transfo and Line.

**Comment by flo-dup** [comment]
In the SMIB.dyd file there's now a parFile and static refs for StandardBus (and also for InfiniteBus), so we need to investigate, and add a unit test for StandardBus. Adding integration test with SMIB test case would be nice too!
