### ISSUE TITLE
Wrong GeneratorPV variable name

### ISSUE THREAD

**Issue by flo-dup** [powsybl/powsybl-dynawo#223]
### Describe the current behavior

GeneratorPV corresponds to OmegaRefGeneratorControllable java class, which returns `generator_deltaPmRefPu_value` for `getDeltaPVarName()`. This variable is not known on dynawo side, leading to an explicit error.

### Describe the expected behavior

Fix the variable name `generator_deltaPmRefPu_value`

**Comment by gautierbureau** [comment]
It's a Dynawo version problem, in v1.4.x the variable is not there... we will need to update the version

**Comment by gautierbureau** [comment]
It's ok with latest 1.5.x
