### ISSUE TITLE
Contextual information for DSLException

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-dynawo#55]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When this DSL is not well filled by a user, exceptions are thrown. The message give the field that is not set or invalid, but some contextual information is missing. For instance, `staticId` or `parameterSetId` are used for all models and it would be helpful to give more information, for instance the class name (CurrentLimitAutomaton::staticId), and if possible the line number in the script (I don't know if it's possible or not).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Have more information when there is an error in the DSL

* **What is the motivation / use case for changing the behavior?**
Have a more user-friendly software

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by flo-dup** [comment]
Checks done in the builders beforehand and results reported.
