### ISSUE TITLE
Ensure equipments - dynamicModels associations

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-dynawo#56]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
With the current implementation it's allowed to associate a dynamic model to an equipment that doesn't exist or an invalid equipment (associate a generator model to a line). Currently, there is no check in the DSL and the errors in the logfile is not easy to understand from a user point of view (the number of equations is not OK).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Check that the staticId exists in the network and the equipment type is compatible

* **What is the motivation / use case for changing the behavior?**
Have a more user-friendly software

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by Lisrte** [comment]
Fixed by #194
