### ISSUE TITLE
Aliases for long keywords

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-dynawo#59]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Some keywords in the DSL are really long. Most of them correspond to the name of the dynamic model in Dynawo. It's really easy to write the wrong name that lead to a syntax error, but it could be nice if the user (or the integration) has a way to define its own alias.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Be able to define custom aliases for really long keywords to avoid mistyping:
```
alias gs4w = GeneratorSynchronousFourWindings
```

* **What is the motivation / use case for changing the behavior?**
Make the DSL more user-friendly

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by flo-dup** [comment]
Aliases available through the models.json file.
No custom aliases available (nor requested).
