### ISSUE TITLE
Module refactoring

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-dynawo#67]
* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
We have a single Maven module

* **What is the expected behavior?**
As discussed with @mathbagu we propose to split the code in 3 Maven modules
 - dynaflow
 - dynawaltz
 - dynawaltz-dsl

The idea behind dynawaltz-dsl is to move everything related to Groovy DSL into its own module and maybe allows using another kind of DSL (like Python or Kotlin one), so that dynaflow and dynawaltz do not have any Groovy dependency.

* **What is the motivation / use case for changing the behavior?**

To have a better code organization.

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by zamarrenolm** [comment]
Just one doubt about **naming** of modules and related code. A short explanation is required before asking the question.

Currently there are two PowSyBl APIs implemented in the project: `LoadFlow` and `DynamicSimulation`.

`LoadFlow` is implemented as a direct call to DynaFlow launcher, passing it only the IIDM Network and some parameters. The DynaFlow launcher is a C++ module in dynawo project (https://github.com/dynawo/dynaflow-launcher). We understand it is responsible for preparing required Dynawo simulation, establishing the mapping between Network equipment and dynamic models, setting its parameters, and executing the Dynawo simulation using a job file. In current version of DynaFlow integration we do not see how the results are put back in the Network, but we assume Dynawo will export an updated XIIDM that could be read after simulation has finished. 
 
`DynamicSimulation` is implemented using a set of Dynawo-named classes that perform a similar function to what DynaFlow launcher is doing: they map Network equipment to dynamic models, assign its parameters and prepare the dynamic simulation building a job file. Currently results are recovered as curves in PowSyBl time series objects.

Our doubt is if we should **rename** all current Dynawo-named code to DynaWaltz-prefixed OR we keep it as it is, as current code in powsybl-dynawo could (eventually) support also the integration of the different flavors of Dynawo (DynaSwing, DynaWave, ...). In fact, what is done in DynaFlow launcher is functionally very similar to what is done in Java powsybl-dynawo integration ... we assume there is a specific launcher for DynaFlow for optimization purposes (and maybe hiding the complexity of the mapping to the user).

**Comment by zamarrenolm** [comment]
On the other side, we understand that the current integration of Dynawo as an implementation of PowSyBl `DynamicSimulation` API, letting the user define the mapping with dynamic models is mainly oriented towards the use of Dynawo in its DynaWaltz flavour. So, we agree on renaming the related modules, files and classes. 

Just wanted to confirm.

**Comment by geofjamg** [comment]
> (and maybe hiding the complexity of the mapping to the user).

Maybe I am wrong I think that if dynaflow launcher main purpose is to be able to optimize the (future) security analysis in more internal loop that what could have be done on Java integration side. @mathbagu do you remenber if it was the reason?

**Comment by geofjamg** [comment]
> On the other side, we understand that the current integration of Dynawo as an implementation of PowSyBl `DynamicSimulation` API, letting the user define the mapping with dynamic models is mainly oriented towards the use of Dynawo in its DynaWaltz flavour. So, we agree on renaming the related modules, files and classes.
> 
> Just wanted to confirm.

That's a good question, I have not idea if what has been done for the dynawaltz will be reusable or not (or some part) for dynaswing.
Maybe one day we will have a dynawo core module shared by dynawaltz and dynaswing integrations? 
But for now as we we are very far from a dynaswing integration we should stay on proposed renaming and see later on.
@zamarrenolm @mathbagu are you ok?

**Comment by zamarrenolm** [comment]
Agree. 
Will proceed with the proposed renaming and consider the current Java integration as DynaWaltz integration.

**Comment by rosiereflo** [comment]
DynaFlow was initially supposed to be integrated similarly to DynaWaltz. However our deadline and PowSybl team free time were not compatible so we had to go with this DynaFlow-Launcher solution. Most of the code of the DynaWaltz integration in PowSybl will be reusable for DynaSwing (it is mostly the models library and mapping that will change). On the end I don't know what the naming should be but I wanted to make sure you had the full context before taking a decision.

**Comment by zamarrenolm** [comment]
By the way @rosiereflo: in the current master branches of dynaflow-launcher and powsybl-dynawo integration I have not been able to see if the IIDM Network is updated after the calculation. Is this function already implemented ? is it being developed in a separate branch ?

**Comment by rosiereflo** [comment]
You are perfectly right, this is something that we have to do but it is not started yet
